[build]
  command = "npm run build:prod"
  publish = "dist/" 
  
  [[redirects]]
  from = "/api/*"
  to = "https://fikingtrader-slnnd.ondigitalocean.app/api/:splat"
  status = 200
  force = true


  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

